### ISSUE TITLE
New line character \n is not properly converted.

### ISSUE THREAD

**Issue by neestell** [iflutter/intl_manager#2]
Android locatization files `strings-xx.xml` may contain `\n` characters. If I try to convert ones using **intl_manager** additional \ will be added for every \n character but it break down new line element.
For example: `<string name="hello">Hello\nworld!</string>`
Result:     `"hello" : MessageLookupByLibrary.simpleMessage("Hello\\nworld!"),`
UI result: Hello\nworld!

**Comment by shenkaige** [comment]
> Android locatization files `strings-xx.xml` may contain `\n` characters. If I try to convert ones using **intl_manager** additional \ will be added for every \n character but it break down new line element.
> For example: `<string name="hello">Hello\nworld!</string>`
> Result: `"hello" : MessageLookupByLibrary.simpleMessage("Hello\\nworld!"),`
> UI result: Hello\nworld!

Thanks for your feedback，`\b, \t, \n, \a, \r` was supported now.you can get the support from v0.0.4.
[https://pub.dev/packages/intl_manager](https://pub.dev/packages/intl_manager)
