### ISSUE TITLE
Upgrade required

### ISSUE THREAD

**Issue by neestell** [iflutter/intl_manager#3]
Please upgrade dependencies for your plugin
`Because intl_manager 0.0.4 depends on intl ^0.15.7 and no versions of intl_manager match >0.0.4 <0.1.0, intl_manager ^0.0.4 requires intl ^0.15.7.
So, because app depends on both intl ^0.16.0 and intl_manager ^0.0.4, version solving failed.
`

**Comment by shenkaige** [comment]
> Please upgrade dependencies for your plugin
> `Because intl_manager 0.0.4 depends on intl ^0.15.7 and no versions of intl_manager match >0.0.4 <0.1.0, intl_manager ^0.0.4 requires intl ^0.15.7. So, because app depends on both intl ^0.16.0 and intl_manager ^0.0.4, version solving failed. `

Thanks for your report. I had changed the package  depends type of 'intl',you can try like this:

```
  intl_manager:
    git: 'https://github.com/iflutter/intl_manager'
```

if the problem fixed,I will publish 'intl_manager' to pub.dev

**Comment by neestell** [comment]
Thanks works fine!
