### ISSUE TITLE
Version solving

### ISSUE THREAD

**Issue by neestell** [iflutter/intl_manager#4]
**Flutter sdk** has been updated to version **1.12**. Please apply a version compatibility for your library. Thanks!

**Comment by shenkaige** [comment]
> **Flutter sdk** has been updated to version **1.12**. Please apply a version compatibility for your library. Thanks!

The version problem has been solved now.Please upgrade 'intl_manager' to  0.0.4+2.Thanks.

**Comment by neestell** [comment]
Ok thanks!
